server:
  port: 8080
  #  开启SSL
  ssl:
    enabled: true
    key-store: classpath:jks/webclient.p12
    key-store-password: ouyushan.pass
    key-alias: webclient
    key-password: ouyushan.pass
    # 用于双向认证
    client-auth: need
    trust-store: classpath:jks/webserver.keystore
#    trust-store-type: jks
    trust-store-password: ouyushan.pass
