package org.ouyushan.cxf.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.0
 * 2020-11-07T21:13:40.283+08:00
 * Generated source version: 3.4.0
 *
 */
@WebService(targetNamespace = "http://ws.cxf.ouyushan.org/", name = "UserService")
@XmlSeeAlso({ObjectFactory.class})
public interface UserService {

    @WebMethod
    @RequestWrapper(localName = "getUserList", targetNamespace = "http://ws.cxf.ouyushan.org/", className = "org.ouyushan.cxf.ws.GetUserList")
    @ResponseWrapper(localName = "getUserListResponse", targetNamespace = "http://ws.cxf.ouyushan.org/", className = "org.ouyushan.cxf.ws.GetUserListResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.cxf.ouyushan.org/")
    public java.util.List<User> getUserList(

        @WebParam(name = "userId", targetNamespace = "http://ws.cxf.ouyushan.org/")
        String userId
    );

    @WebMethod
    @RequestWrapper(localName = "getUserName", targetNamespace = "http://ws.cxf.ouyushan.org/", className = "org.ouyushan.cxf.ws.GetUserName")
    @ResponseWrapper(localName = "getUserNameResponse", targetNamespace = "http://ws.cxf.ouyushan.org/", className = "org.ouyushan.cxf.ws.GetUserNameResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.cxf.ouyushan.org/")
    public String getUserName(

        @WebParam(name = "userId", targetNamespace = "http://ws.cxf.ouyushan.org/")
        String userId
    );

    @WebMethod
    @RequestWrapper(localName = "getUser", targetNamespace = "http://ws.cxf.ouyushan.org/", className = "org.ouyushan.cxf.ws.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://ws.cxf.ouyushan.org/", className = "org.ouyushan.cxf.ws.GetUserResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.cxf.ouyushan.org/")
    public User getUser(

        @WebParam(name = "userId", targetNamespace = "http://ws.cxf.ouyushan.org/")
        String userId
    );
}
