server:
  port: 8080
  keystore-alias: webclient
  #  开启SSL
  ssl:
    key-store: classpath:jks/webclient.p12
    key-store-password: ouyushan.pass
    key-alias: webclient
    key-password: ouyushan.pass
    enabled: true

cxf:
  path: /ws