package org.ouyushan.ws.client.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.0
 * 2020-11-04T16:00:55.936+08:00
 * Generated source version: 3.4.0
 *
 */
@WebService(targetNamespace = "http://cxf.ouyushan.org/", name = "UserService")
@XmlSeeAlso({ObjectFactory.class})
public interface UserService {

    @WebMethod
    @RequestWrapper(localName = "getUser", targetNamespace = "http://cxf.ouyushan.org/", className = "org.ouyushan.cxf.client.ws.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://cxf.ouyushan.org/", className = "org.ouyushan.cxf.client.ws.GetUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public User getUser(

        @WebParam(name = "userId", targetNamespace = "")
        String userId
    );

    @WebMethod
    @RequestWrapper(localName = "getAllUserData", targetNamespace = "http://cxf.ouyushan.org/", className = "org.ouyushan.cxf.client.ws.GetAllUserData")
    @ResponseWrapper(localName = "getAllUserDataResponse", targetNamespace = "http://cxf.ouyushan.org/", className = "org.ouyushan.cxf.client.ws.GetAllUserDataResponse")
    @WebResult(name = "Map", targetNamespace = "")
    public GetAllUserDataResponse.Map getAllUserData()
;

    @WebMethod
    @RequestWrapper(localName = "getUserName", targetNamespace = "http://cxf.ouyushan.org/", className = "org.ouyushan.cxf.client.ws.GetUserName")
    @ResponseWrapper(localName = "getUserNameResponse", targetNamespace = "http://cxf.ouyushan.org/", className = "org.ouyushan.cxf.client.ws.GetUserNameResponse")
    @WebResult(name = "String", targetNamespace = "")
    public String getUserName(

        @WebParam(name = "userId", targetNamespace = "")
        String userId
    );
}
