server:
  port: 8080
  #  开启SSL
    #    enabled: true
    #    key-store: classpath:jks/webserver.keystore
    #    key-store-password: ouyushan.pass
  key-alias: webclient
#    key-password: ouyushan.pass
